import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "notebooks" / "01_seed_lakehouse.ipynb"


def make_cell(cell_id, source, kind="code", metadata=None):
    cell = {"id": cell_id, "cell_type": kind, "metadata": metadata or {},
            "source": source.splitlines(keepends=True)}
    if kind == "code":
        cell.update(execution_count=None, outputs=[])
    return cell


def build_notebook():
    acceptance = json.loads((ROOT / "tests" / "acceptance-cases.json").read_text())
    query = (ROOT / "tests" / "validation.sql").read_text()
    cells = [
        make_cell("overview", "# Fabric IQ supply-chain demo\n\n"
                  "Generated by build_notebook.py; do not edit generated data functions.\n"
                  "Use a dedicated, schema-enabled Lakehouse in the same workspace.\n"
                  "Attach it as the default Lakehouse and restart the Spark session.\n"
                  "No cloud resources, capacities or tenant settings are created here.\n"
                  "Writes are sequential, not a transaction across five tables. Stop readers and graph refreshes during replacement.\n"
                  "This notebook has not yet been executed in Fabric.\n", "markdown"),
        make_cell("parameters", 'WORKSPACE_ID = ""\nLAKEHOUSE_ID = ""\n'
                  'CONFIRMATION = ""\nSCENARIO = "initial"\nWRITE_MODE = "create"\n',
                  metadata={"tags": ["parameters"]}),
        make_cell("dataset", (ROOT / "seed.py").read_text()),
        make_cell("writer", (ROOT / "fabric_load.py").read_text()),
        make_cell("preview", 'tables = build_tables(SCENARIO)\n'
                  'print({name: len(rows) for name, rows in tables.items()})\n'
                  'print([row for row in tables["order_lines"] if row["shortageQty"]])\n'),
        make_cell("write-warning", "## Explicit write gate\n\n"
                  "Fill both IDs and set CONFIRMATION to `WRITE_DEMO_TABLES` only after checking the target.\n"
                  "`create` refuses existing tables. To replenish use SCENARIO=`replenished`, WRITE_MODE=`replace-demo`.\n"
                  "To reset use SCENARIO=`initial`, WRITE_MODE=`replace-demo`. Replacement requires the ownership property.\n"
                  "Never run multiple writers or change Lakehouse names/schema during this notebook.\n", "markdown"),
        make_cell("write", 'import notebookutils\n\n'
                  'namespace = write_fabric_tables(\n'
                  '    spark, tables, dict(notebookutils.runtime.context),\n'
                  '    WORKSPACE_ID, LAKEHOUSE_ID, CONFIRMATION, WRITE_MODE\n)\n'
                  'print(f"Verified five demo tables in {namespace}")\n'),
        make_cell("verify", f"validation_sql = {query!r}\n"
                  f"expected_by_scenario = {acceptance['expectedRows']!r}\n"
                  'actual = [row.asDict() for row in spark.sql(validation_sql).collect()]\n'
                  'if actual != expected_by_scenario[SCENARIO]:\n'
                  '    raise RuntimeError(f"Acceptance mismatch: {actual}")\n'
                  'print({"scenario": SCENARIO, "verifiedShortages": actual})\n'),
        make_cell("next", "## Next: Ontology\n\n"
                  "Follow entity-mapping.md to bind the five managed Delta tables.\n"
                  "Refresh the ontology graph after initial ingestion, replenishment and reset.\n"
                  "Run the agent questions in acceptance-cases.json three times per scenario.\n"
                  "Passing this notebook verifies only Delta ingestion and SQL, not the ontology or agent.\n", "markdown"),
    ]
    return {"cells": cells, "metadata": {
        "kernelspec": {"display_name": "Synapse PySpark", "language": "python", "name": "synapse_pyspark"},
        "language_info": {"name": "python"}}, "nbformat": 4, "nbformat_minor": 5}


def main():
    parser = argparse.ArgumentParser(description="Build or check the self-contained Fabric notebook")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = json.dumps(build_notebook(), indent=2, ensure_ascii=True) + "\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            raise SystemExit("Notebook is missing or stale; run python3 build_notebook.py")
        print("Notebook matches its tested sources")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered)
        print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()